services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale-obs
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_HOSTNAME=${TS_HOSTNAME:-obs-stack}
      - TS_USERSPACE=false
    volumes:
      - tailscale-data:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped
    networks:
      - obs-network

volumes:
  tailscale-data:

networks:
  obs-network:
    external: true
    name: obs-network
