{
 "title": "App + Server metrics Copy",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "job", "query": { "query": "label_values(job)" } },
   { "name": "filter" },
   { "name": "filters" }
  ]
 },
 "panels": [
  {
   "title": "API Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"medicaments-api\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "bargauge",
   "description": "Resource pressure via PSI",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(node_pressure_cpu_waiting_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "CPU"
    },
    {
     "expr": "irate(node_pressure_memory_waiting_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "Mem"
    },
    {
     "expr": "irate(node_pressure_io_waiting_seconds_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "I/O"
    }
   ]
  },
  {
   "title": "File Descriptors Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(process_open_fds{job=\"$job\", instance=\"$instance\"} * 100) / process_max_fds{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_total{job=\"$job\",instance=\"$instance\",status=~\"5..\"}[5m])) / sum(rate(http_request_total{job=\"$job\",instance=\"$instance\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In flight requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_in_flight{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Go gc duration",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{instance=\"$instance\", job=\"$job\", quantile=\"1\"} * 1000",
     "legendFormat": "Goroutines"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Goroutines"
    }
   ]
  },
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Heap In Use"
    },
    {
     "expr": "go_memstats_alloc_bytes{instance=\"$instance\", job=\"$job\"}",
     "legendFormat": "Heap Alloc"
    }
   ]
  },
  {
   "title": "App CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$job\", instance=\"$instance\"}[$__rate_interval]) * 100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Top 5 Endpoints by Request Rate (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "topk(10, sum by(path) (increase(http_request_total{job=\"$job\", instance=\"$instance\"}[5m]))) > 0",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Top 5 Slowest Endpoints (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(path, le) (rate(http_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[5m]))) * 1000",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Request Rate by Status Code",
   "type": "timeseries",
   "description": "Requests over the last 5m",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "req" } },
   "targets": [
    {
     "expr": "sum by(status) (increase(http_request_total{job=\"$job\"}[5m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Response Time (Latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (\n  rate(http_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])\n)) * 1000",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (\n  rate(http_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])\n)) * 1000",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (\n  rate(http_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$__rate_interval])\n)) * 1000",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Request duration heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "targets": [
    {
     "expr": "sum by(le) (rate(http_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Status Codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(status_code) (count_over_time({job=\"$job\"} |= `\"status_code\"` |~ `(?i)$filter` | json path=\"path\" [$__auto]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Log Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(level) (count_over_time({job=\"medicaments-api\"} |~ `(?i)$filter` [$__range]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Log Levels",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(level) (count_over_time({job=\"$job\"} |~ `.+` | json path=\"path\" [$__auto]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Raw Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"$job\"} |~ `(?i)$filter` | json path=\"path\"",
     "maxLines": 1200
    }
   ]
  }
 ]
}